---
title: "R Notebook"
output: html_notebook
---

*** Analysis of binary data ***

# 1. Read the Logistic.txt into R.

```{r}
data <- read.delim("Logistic.txt",header = TRUE, sep = "", dec = ".")
head(data,2) 
table(data)
margin.table(data)
```
*** Fitting data to binomial distribution ***


```{r}
# Define the column and row names.
rownames = c("AZT Yes", "AZT No")
colnames = c("AIDS Yes", "AIDS No")

P <- matrix(c(25,170,44,168), nrow = 2, byrow = TRUE, dimnames = list(rownames, colnames))
print(P)
barplot(P,
main = "Survival of Each Class",
ylab = "Frequency",
col = c("darkred","darkblue")
)
legend("topleft",
c("AZT No","AZT Yes"),
fill = c("darkred","darkblue")
)

```
*** Comparing the two groups ***
Since the p-value is below 0.05, we can reject the null hypothesis, and the two group are significantly different from each other.

```{r}
# Kode er tyvstjålet fra Jan
## AIDS yes
n1 <- sum(data[,2])
x1 <- data[1,2]

## AIDS no
x2 <- data[1,3]
n2 <- sum(data[,3])

## chiÂ² test directly in R
prop.test(c(x1,x2), c(n1, n2))


## Log odds
(theta <- log(x1/(n1-x1)*(n2-x2)/x2))


## Plot
loglik.fun <- function(theta, eta, x, n){
    a <- exp(theta + eta)
    b <- exp(eta)
    x[1] * theta + (x[1] + x[2]) * eta - n[1] *
        log(1 + a) - n[2] * log(1 + b)
}


eta <- seq(-0.5,0.5,length=100)
theta <- seq(-2,2,length=100)


par(mfrow=c(1,2))
ll<- outer(theta,eta,'loglik.fun', x=c(x1,x2), n=c(n1,n2))
like<- exp(ll-max(ll))
contour(theta,eta,like,level=c(0.05,.1,.3,.5,.7,.9),
        xlab=expression(theta),
        ylab=expression(eta))
  title(expression('Likelihood contour'))
abline(v = 0, col="red", lwd=3, lty=2)
#lines(c(0,0),c(0,2),lty=2,col=2)

## profile likelihood
lp.theta <- function(theta,x,n){
    fun.tmp <- function(eta,theta,x,n){
        loglik.fun(theta, eta, x, n)
    }
    ## interval from plot
    optimise(fun.tmp,c(-20,20),theta=theta,
             x=x, n=n,maximum=TRUE)$objective
}


lp <- sapply(theta,lp.theta,x=c(x1,x2),n=c(n1,n2))

lp <- lp - max(lp)

plot(theta,exp(lp),type="l")
lines(c(-2,10),exp(-qchisq(0.95,df=1)/2)*c(1,1), col=2)
lines(c(0,0),c(0,1),col=4,lty=2,lwd=2)
 title(expression('Profile Likelihood'))
## So we cannot reject that p1=p2

```
*** Estimate parameters in the model ***









