


Estimation of model parameters (p0, p1)
Report confidence interval for parameter describing the difference

```{r}
data <- read.delim("Logistic.txt",header = TRUE, sep = "", dec = ".")
data$AIDS_no=data$n-data$AIDS_yes
head(data,2) 
 



```

```{r}
# Values as described on pp. 78
x=data$AIDS_yes[1]
y=data$AIDS_yes[2]
m=data$n[1]
n=data$n[2]
N=m+n
t=x+y

```
```{r}
# Example 4.4

x<- 25; m<- 170
y<- 44; n<- 168

that<- log(x/(m-x)*(n-y)/y)
se2<- 1/x + 1/(m-x) + 1/y + 1/(n-y)
se<- sqrt(se2)

ehat<- log(y/(n-y))
#print(c(that,ehat))
cat('theta-hat=',that,',  se=',se,'\n')

# plots
par(mfrow=c(2,2))
th<- seq(-2,2,len=1000)
et<- seq(-2,0,len=1000)

fun1<- function(theta,eta){
  a <- exp(theta+eta)
  b<- exp(eta)
  x*theta + (x+y)*eta - m*log(1+a) - n*log(1+b)
}

ll<- outer(th,et,'fun1')
like<- exp(ll-max(ll))
contour(th,et,like,level=c(.1,.3,.5,.7,.9),
        xlab=expression(theta),
        ylab=expression(eta))
title(expression('Likelihood contour'))
abline(v=that,h=ehat,lwd=.4)

lik1<- apply(like,1,max)
plot(th,lik1,type='n',xlab=expression(theta),
     ylab='Likelihood')
lines(th,lik1)
abline(h=.15,lwd=.4)
abline(v=0)
title(expression('Profile likelihood'))

# getting likelihood of H0
a<- approx(th,lik1,xout=0)$y
print(a)

# getting likelihood interval
#a <- li(th,lik1,0.15)
#cat('95% CI for theta=',a,'\n')

# finding optimal parameters
fun2<- function(th){
  theta = th[1]
  eta = th[2]
  a <- exp(theta+eta)
  b <- exp(eta)
  -(x*theta + (x+y)*eta - m*log(1+a) - n*log(1+b))
}
opt <- nlminb(c(0, 0), fun2)
(opt$par)


```

